### ISSUE TITLE
Add OnConnectionDown callback in autopaho

### ISSUE THREAD

**Issue by thedevop** [eclipse-paho/paho.golang#280]
**Is your feature request related to a problem? Please describe.**
Autopaho will continuously reconnect to the server once it is started. There are situations where upper layer needs visibility when the connection to the broker is lost, and under certain conditions not continue to the reconnect.

**Describe the solution you'd like**
Add a OnConnectionDown callback, with this signature:
```go
OnConnectionDown func() bool 
// or
OnConnectionDown func(*ConnectionManager) bool 
```
The returned value determines if ConnectionManager should continue the mainloop to reconnect.

**Additional context**
If this is ok, I can provide an implementation.

**Comment by MattBrittan** [comment]
I'm open to this. However the comments will need to clearly indicate that it's only called when a fully established connection (i.e. `CONNACK` indicating all is good has been received) and `OnConnectError` is called in other cases. I do wonder if it would be better to just use the `context` to stop future reconnection attempts (just so there is one, and only one, way to accomplish this) but am open to either option.

**Comment by thedevop** [comment]
If you're ok with this [implementation](https://github.com/thedevop/paho.golang/tree/OnConnectionDown), I'll create a PR.

**Comment by MattBrittan** [comment]
Looks OK. Could you just add to the comment along the lines of "Returning false will casue autopaho to cease attempting to connect" or something similar (so it appears in the docs).

**Comment by thedevop** [comment]
Please review the PR, the comment now shows:
`Only called after the connection that resulted in OnConnectionUp is dropped. Returning false will cause autopaho to cease attempting to connect. Supplied function must not block.`

**Comment by MattBrittan** [comment]
Added in PR #281
