### ISSUE TITLE
router.go doesn't match() topic correctly

### ISSUE THREAD

**Issue by wxmeng04** [eclipse-paho/paho.golang#284]
**Describe the bug**
The match() function in router.go seems  workings unproperly. Find below cases:
```
route: "abc/#/mmm", topic: "abc/ddd/eee/eee". It should mismatch, but match() return true
route: "abc/#/", topic: "abc". It should mismatch, but match() return true
route: "abc/#/+", topic: "abc". It should mismatch, but match() return true
```
It is only my judgement, but may be incorrect. In any case please find below quote from IEC standard 20922.
```
4.7.3 Topic semantic and usage
The following rules apply to Topic Names and Topic Filters: 
 All Topic Names and Topic Filters MUST be at least one character long [MQTT-4.7.3-1] 
 Topic Names and Topic Filters are case sensitive 
 Topic Names and Topic Filters can include the space character 
 A leading or trailing ‘/’ creates a distinct Topic Name or Topic Filter 
 A Topic Name or Topic Filter consisting only of the ‘/’ character is valid
```

**To reproduce**
Code and steps that reproduce the behaviour

**Debug output**
Any debugging output provided by the client code while reproducing the bug (either embedded to link to the output)

**Expected behaviour**

**Software used:**
- Server was X version Y
- Client version X (git sha if not a released version)

**Additional context**

**Comment by wxmeng04** [comment]
Find also below statement of 7.1.3 of IEC standard 20922.
```
 “+/tennis/#” is valid
 “sport+” is not valid
 “sport/+/player1” is valid
 “/finance” matches “+/+” and “/+”, but not “+”
```

**Comment by MattBrittan** [comment]
From the spec:

> The number sign (‘#’ U+0023) is a wildcard character that matches any number of levels within a topic. The multi-level wildcard represents the parent and any number of child levels.
